export const GET_ALL_TIMER_SUCCESS = 'GET_ALL_TIMMER_SUCCESS';
export const CREATE_TIMER_SUCCESS = 'CREATE_TIMER_SUCCESS';
export const UPDATE_TIMER_SUCCESS = 'UPDATE_TIMER_SUCCESS';
export const DELETE_TIMER_SUCCESS = 'DELETE_TIMER_SUCCESS';
export const SET_SELECTED_TIMER = 'SET_SELECTED_TIMER';
export const CLEAR_TIMER = 'CLEAR_TIMER';

export const UPDATE_TIMER_TOTAL_DURATION = 'UPDATE_TIMER_TOTAL_DURATION';

export const CREATE_DAY_SESSION_SUCCESS = 'CREATE_DAY_SESSION_SUCCESS';
export const UPDATE_DAY_SESSION_SUCCESS = 'UPDATE_DAY_SESSION_SUCCESS';